### ISSUE TITLE
fails to build when using pods structure

### ISSUE THREAD

**Issue by sethwebster** [rmmmp/ember-cloud-firestore-adapter#11]
```
Build failed.
Build Error (Concat)

ENOENT: no such file or directory, open '/Users/xxxxxxxx/development/cfireview/clean-pods/tmp/source_map_concat-input_base_path-i7wWgn1z.tmp/node_modules/firebase/firebase-firestore.js'`

```
```=================================================================================

ENV Summary:

  TIME: Sat Jan 27 2018 20:54:24 GMT-0500 (EST)
  TITLE: ember
  ARGV:
  - /Users/xxxxxxxx/.nvm/versions/node/v8.9.4/bin/node
  - /usr/local/bin/ember
  - build
  EXEC_PATH: /Users/xxxxxxxx/.nvm/versions/node/v8.9.4/bin/node
  TMPDIR: /var/folders/y_/z1hh7_lj6vd814ycqvqp6g2c0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/xxxxxxxx/.nvm/versions/node/v8.9.4/bin
  - /Users/xxxxxxxx/anaconda3/bin
  - /Users/xxxxxxxx/.dnx/bin
  - /usr/local/heroku/bin
  - /Users/xxxxxxxx/.rbenv/shims
  - /Users/xxxxxxxx/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 90284032
  TOTALMEM: 17179869184
  UPTIME: 119661
  LOADAVG: 2.96044921875,2.6064453125,2.76611328125
  CPUS:
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz - 2800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.4
  - openssl: 1.0.2n
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '/Users/xxxxxxxx/development/cfireview/clean-pods/tmp/source_map_concat-input_base_path-i7wWgn1z.tmp/node_modules/firebase/firebase-firestore.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SourceMap.addFile (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (<anonymous>)
    at Concat.<anonymous> (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/fast-sourcemap-concat/lib/source-map.js:419:12
    at initializePromise (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/rsvp/dist/rsvp.js:1039:33)
    at SourceMap.end (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/fast-sourcemap-concat/lib/source-map.js:406:10)
  - codeFrame: ENOENT: no such file or directory, open '/Users/xxxxxxxx/development/cfireview/clean-pods/tmp/source_map_concat-input_base_path-i7wWgn1z.tmp/node_modules/firebase/firebase-firestore.js'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Concat` plugin. 💥
ENOENT: no such file or directory, open '/Users/xxxxxxxx/development/cfireview/clean-pods/tmp/source_map_concat-input_base_path-i7wWgn1z.tmp/node_modules/firebase/firebase-firestore.js'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `Concat` plugin. 💥
ENOENT: no such file or directory, open '/Users/xxxxxxxx/development/cfireview/clean-pods/tmp/source_map_concat-input_base_path-i7wWgn1z.tmp/node_modules/firebase/firebase-firestore.js'
  - name: Error
  - nodeAnnotation: Concat
  - nodeName: Concat
  - originalErrorMessage: ENOENT: no such file or directory, open '/Users/xxxxxxxx/development/cfireview/clean-pods/tmp/source_map_concat-input_base_path-i7wWgn1z.tmp/node_modules/firebase/firebase-firestore.js'
  - stack: Error: ENOENT: no such file or directory, open '/Users/xxxxxxxx/development/cfireview/clean-pods/tmp/source_map_concat-input_base_path-i7wWgn1z.tmp/node_modules/firebase/firebase-firestore.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SourceMap.addFile (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (<anonymous>)
    at Concat.<anonymous> (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/fast-sourcemap-concat/lib/source-map.js:419:12
    at initializePromise (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/rsvp/dist/rsvp.js:1039:33)
    at SourceMap.end (/Users/xxxxxxxx/development/cfireview/clean-pods/node_modules/fast-sourcemap-concat/lib/source-map.js:406:10)

=================================================================================
```

**Comment by rmmmp** [comment]
@sethwebster, few questions that will help debug the error

- What Ember, Ember Data, and Ember CLI version are you using?
- Are you also using EmberFire?
- What Firebase version is downloaded in your `node_modules` folder?

**Comment by sethwebster** [comment]
Ember: 2.18.0
Yes
"firebase": "3.9.0"

**Comment by sethwebster** [comment]
@rmmmp I have created a test project that fails:
https://github.com/sethwebster/clean-pods

**Comment by rmmmp** [comment]
@sethwebster, I didn't check out your repo but you can't use EmberFire with this adapter right now because EmberFire depends on Firebase 3.x which isn't compatible with Cloud Firestore if I'm correct. Removing EmberFire and updating firebase to 4.x should make things work.

**Comment by sethwebster** [comment]
@rmmmp - great I'll give that a shot.

**Comment by sethwebster** [comment]
Confirmed. Thanks!
